language: node_js
before_install:
  - npm install npm -g
node_js:
  - 5
  - 4
  - io.js
  - 0.12
  - 0.10
matrix:
  include:
    - node_js: 4
      env: TEST_SUITE=standard
env:
  - TEST_SUITE=coverage
  - TEST_SUITE=integration
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
sudo: false
